### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anuraggupta322**

### CODE REVIEW

**Comment by anuraggupta322** [comment]
yes

**Comment by anuraggupta322** [comment]
yes

**Comment by Maikuolan** [comment]
You've just deleted half the README and replied repeatedly with "yes" to your own pull request. Looks a little spammy. What is the purpose of this pull request?

**Comment by FredrikAugust** [comment]
Smells like someone trying to get their t-shirt. You just deleted parts of our README.

Please refrain from creating more PRs.

**Comment by Maikuolan** [comment]
@FredrikAugust Considering that you've closed this pull requests already anyway, I'm not sure whether it will actually make any difference at all, but based on the information shown under *"Legend"* when checking profiles at the Hacktoberfest website this year (specifically, the description for *"Invalid"*), I would recommend adding the `invalid` label to this pull request, just to be safe.

**Pull request closed without merging**
