### PR TITLE
small correction to the word open-source

### PR DESCRIPTION
**Pull request by spencer1573**
open source could open-source ... totally understand if you don't want to change it. thanks!

### CODE REVIEW

**Comment by Maikuolan** [comment]
Not super important IMO, and I usually ignore the subject of "open source" versus "open-source" to avoid pedantry and nitpickiness (or, in some cases, the risk of being yelled at by maintainers, depending on the mood/nature of the maintainers at the repository in question), but seeing as this PR already exists now, my own two cents on this subject:

If we're talking about "open source" as a noun in its own right (or alternatively, "open" as a preceding adjective describing the noun, "source"), there should *not* be any hyphen.

If we're talking about "open-source ideas" (i.e., "open-source" as a preceding *compound* adjective describing describing the noun, "ideas"), there *should* be a hyphen.

*See: https://www.grammarbook.com/punctuation/hyphens.asp*

**Comment by spencer1573** [comment]
sounds good. feel free to close this one.

**Comment by FredrikAugust** [comment]
Thank you for the thorough explanation @Maikuolan <3

**Comment by Maikuolan** [comment]
You're welcome; Happy to help. :-)

**Pull request closed without merging**
